# Generated by Django 5.0 on 2024-02-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Expenses', models.IntegerField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
